urls = [
["https://www.youtube.com/watch?v=ro4yhp9L6Ok","WAR","Lowrider"],
["https://www.youtube.com/watch?v=RFSWW4O6QNM","WAR","Slipping Into Darkness"],
["https://www.youtube.com/watch?v=6LjxfNxbZM4&index=2&list=PLD6F3675FAAAE5498","Rosie & The Originals","Angel Baby"],
["https://www.youtube.com/watch?v=_9X9RpU4hSM&index=4&list=PLD6F3675FAAAE5498","Unkown","When a Boy Loves a Girl"],
["https://www.youtube.com/watch?v=DWQCBuyEKCc&index=11&list=PLD6F3675FAAAE5498","James Brown","Try Me"],
["https://www.youtube.com/watch?v=gj_gW9XY3EQ&index=14&list=PLD6F3675FAAAE5498","Donnie Elbert","What Can I Do"],
["https://www.youtube.com/watch?v=435ujs-NWGc&list=PLD6F3675FAAAE5498&index=15","Little Anthony and The Imperials","Tears On My Pillow"],
["https://www.youtube.com/watch?v=RnxYScrIfxE&index=16&list=PLD6F3675FAAAE5498","Sunny Ozuna","Smile Now, Cry Later"],
["https://www.youtube.com/watch?v=rKJsW6DRgeY&index=18&list=PLD6F3675FAAAE5498","Bobby Moore & The Rhythm Aces","Searching For My Baby"],
["https://www.youtube.com/watch?v=OFGDqD9pYak&index=19&list=PLD6F3675FAAAE5498","The Temprees", "Love Can Be So Wonderful"],
["https://www.youtube.com/watch?v=a3O1RT392fY&index=21&list=PLD6F3675FAAAE5498","Billy Stewart","Sitting In The Park"],
["https://www.youtube.com/watch?v=PuQt3fgNqik&index=23&list=PLD6F3675FAAAE5498","Mary Wells","The One Who Really Loves You"],
["https://www.youtube.com/watch?v=i3wvIS28dnE&index=24&list=PLD6F3675FAAAE5498","Mary Wells", "You Beat Me To The Punch"],
["https://www.youtube.com/watch?v=qmTNKNcGOQU&list=RDQMnjDY_Mj9jEo&index=13","Malo","Suavecito"],
["https://www.youtube.com/watch?v=nzLO1GdwN4A&index=16&list=RDQMnjDY_Mj9jEo","Johnny and The Expressions","Something I Want To Tell You"],
["https://www.youtube.com/watch?v=uThnUmWRCCs&index=18&list=RDQMnjDY_Mj9jEo","Smokey Robinson and The Miracles","Ooh Baby Baby"],
["https://www.youtube.com/watch?v=0x4AZHDT-4A&index=19&list=RDQMnjDY_Mj9jEo","Barbara Lynn","You'll Lose a Good Thing"],
["https://www.youtube.com/watch?v=IJ6QayDXA7I&index=20&list=RDQMnjDY_Mj9jEo","Ralphi Pagan", "No Soy De Ti"],
["https://www.youtube.com/watch?v=MaJyUP1GIi4&index=22&list=RDQMnjDY_Mj9jEo","Sly, Slick, and Wicked","Confessing a Feeling"],
["https://www.youtube.com/watch?v=LpsM3IkbrfE&list=RDQMnjDY_Mj9jEo&index=23","Big Jay McNeely","There Is Something On Your Mind"],
["https://www.youtube.com/watch?v=a-SAixfwDwU&list=RDQMnjDY_Mj9jEo&index=27","Rene & Rene", "Lo Mucho Que Te Quiero"],
["https://www.youtube.com/watch?v=Rv_UW8sHsWE&list=RDQMnjDY_Mj9jEo&index=27","Aaron Neville","Tell It Like It Is"],
["https://www.youtube.com/watch?v=hbjQm-4SWY8&index=28&list=RDQMnjDY_Mj9jEo","Bloodstone","Natural High"],
["https://www.youtube.com/watch?v=BD2WrG5723c&index=30&list=RDQMnjDY_Mj9jEo","Tierra","Together"],
["https://www.youtube.com/watch?v=cil0tnmtQH4&list=RDQMnjDY_Mj9jEo&index=28","Tommy James and The Shondells","Crystal Blue Persuasion"],
["https://www.youtube.com/watch?v=COiIC3A0ROM&index=27&list=RDQMnjDY_Mj9jEo","Al Green","Let's Stay Together"],
["https://www.youtube.com/watch?v=YOKq1VmEbtc&list=RDQMnjDY_Mj9jEo&index=27","GQ","I Do Love You"],
["https://www.youtube.com/watch?v=2v8yiDuHAuo&index=29&list=RDQMnjDY_Mj9jEo","The Escorts","Look Over Your Shoulder"],
["https://www.youtube.com/watch?v=CkSfMj8D-7c","Ritchie Valens","We Belong Together"],
["https://www.youtube.com/watch?v=HMcHbh6HBDk","Ritchie Valens","Donna"],
["https://www.youtube.com/watch?v=FvzNeh4Mq1o","The Flamingos","I Only Have Eyes For You"],
["https://www.youtube.com/watch?v=TY4uxdAt4-M","Paul Anka","Put Your Head On My Shoulder"],
["https://www.youtube.com/watch?v=QzhbGaCwBzs","The Ronettes","Be My Baby"],
["https://www.youtube.com/watch?v=wVHAQX5sSaU","Bobby Darin","Dream Lover"],
["https://www.youtube.com/watch?v=lpcWW5UIP6Y&list=RDqmTNKNcGOQU&index=3","El Chicano","Sabor A Mi"],
["https://www.youtube.com/watch?v=v0fBACHaBck&list=RDqmTNKNcGOQU&index=20","Heatwave","Always And Forever"],
["https://www.youtube.com/watch?v=FICEMBph6qY&list=RDqmTNKNcGOQU&index=22","The Dells","Oh What A Night"],
["https://www.youtube.com/watch?v=l7uvW_GU2cs&list=RDqmTNKNcGOQU&index=27","Etta James","I'd Rather Go Blind"],
["https://www.youtube.com/watch?v=4ho5xFantzQ","Ritchie Valens","Sleepwalk"]
]